go_to_goal_controller:
  ros__parameters:
    use_sim_time: true

    cmd_vel_topic: "/cmd_vel"
    odom_topic: "/odom"
    control_rate: 20.0

    # Cambia estos dos para cada prueba
    goal_x: 1.0
    goal_y: 0.0

    distance_tolerance: 0.05
    heading_tolerance: 0.05
    settle_time: 0.50

    max_linear_speed: 0.35
    max_angular_speed: 1.20
    min_linear_speed: 0.03
    min_angular_speed: 0.05

    # Para tu análisis, estos son kv y kw principales
    kp_linear: 0.80
    ki_linear: 0.00
    kd_linear: 0.00

    kp_angular: 2.50
    ki_angular: 0.00
    kd_angular: 0.00

    linear_integral_limit: 0.80
    angular_integral_limit: 1.00

    turn_in_place_threshold: 0.80
