#!/bin/bash
# Mini Challenge 2 - Testing Examples
# Usage: bash test_mini_challenge_2.sh

set -e  # Exit on error

echo "=========================================="
echo "Mini Challenge 2 - Testing Commands"
echo "=========================================="

# Step 1: Build
echo ""
echo "Step 1: Building package..."
echo "$ colcon build --packages-select mobile_robotics"
echo ""

# Step 2: Launch
echo "Step 2: Launching Mini Challenge 2..."
echo ""
echo "Option A: COMBINED (recommended) - launches both path_generator and go_to_goal:"
echo "  $ ros2 launch mobile_robotics mini_challenge_2.launch.py"
echo ""
echo "Option B: SEPARATE - if you need to test components individually:"
echo "  Terminal 1: $ ros2 launch mobile_robotics path_generator.launch.py"
echo "  Terminal 2: $ ros2 launch mobile_robotics go_to_goal.launch.py"
echo ""

# Step 3: Verification
echo "Step 3: Verification Commands"
echo ""
echo "Check that path_generator_node is running:"
echo "  $ ros2 node list | grep path_generator"
echo ""
echo "Check that go_to_goal_node is running:"
echo "  $ ros2 node list | grep go_to_goal"
echo ""
echo "Monitor goals being published (Part 1 - Square Path):"
echo "  $ ros2 topic echo /goal_pose"
echo ""
echo "Monitor velocity commands:"
echo "  $ ros2 topic echo /cmd_vel"
echo ""
echo "Monitor robot odometry:"
echo "  $ ros2 topic echo /odom"
echo ""

# Step 4: Logs
echo "Step 4: View Node Logs"
echo ""
echo "Check path_generator logs (Part 2 sequencing):"
echo "  Should see: '→ Waypoint 0/4: (2.0, 0.0)'"
echo "  Should see: '→ Waypoint 1/4: (2.0, 2.0)'"
echo "  Should see: '=== PATH COMPLETE ===' when finished"
echo ""
echo "Check go_to_goal logs (Control):"
echo "  Should see: 'New goal: (2.0, 0.0)'"
echo "  Should see: 'Goal reached! e_d=0.0123, e_θ=0.0089'"
echo ""

# Step 5: Expected Behavior
echo "Step 5: Expected Behavior"
echo ""
echo "Part 1 - Square Trajectory:"
echo "  1. Robot starts at origin (0, 0)"
echo "  2. Path generator publishes goal (2, 0)"
echo "  3. Go-to-goal controller moves robot to (2, 0)"
echo "  4. Path generator detects goal reached"
echo "  5. Transitions to next waypoint: (2, 2)"
echo "  6. Repeats for (0, 2), then (0, 0)"
echo "  7. Path complete loop starts over"
echo ""
echo "Part 2 - Path Generator Sequencing:"
echo "  - Goals published sequentially (no manual intervention)"
echo "  - Automatic transition between waypoints"
echo "  - Reachability validated on startup"
echo "  - Can adapt gains based on distance (if enabled)"
echo ""

# Step 6: Parameter Configurations
echo "Step 6: Test Different Configurations"
echo ""
echo "For FAST response:"
echo "  Edit config/path_generator_params.yaml:"
echo "    goal_reached_distance: 0.1  # Looser tolerance"
echo "    settle_time: 0.5            # Faster confirmation"
echo ""
echo "For PRECISE control:"
echo "  Edit config/go_to_goal_params.yaml:"
echo "    e_d_tolerance: 0.01         # Tighter distance tolerance"
echo "    e_theta_tolerance: 0.01"
echo "    settle_time: 1.5            # Longer confirmation"
echo ""
echo "For PI CONTROL:"
echo "  Edit config/go_to_goal_params.yaml:"
echo "    k_i_v: 0.05                 # Enable integral for distance"
echo "    k_i_omega: 0.1              # Enable integral for heading"
echo "    i_max_v: 0.2                # Anti-windup limit"
echo "    i_max_omega: 0.8"
echo ""

# Step 7: Troubleshooting
echo "Step 7: Troubleshooting"
echo ""
echo "If robot doesn't move:"
echo "  1. Check /odom is being published: ros2 topic list | grep odom"
echo "  2. Increase k_v in go_to_goal_params.yaml"
echo "  3. Check /cmd_vel is being published: ros2 topic echo /cmd_vel"
echo ""
echo "If robot overshoots:"
echo "  1. Decrease k_v in go_to_goal_params.yaml"
echo "  2. Increase e_d_tolerance for less precision"
echo ""
echo "If waypoint transitions are too fast:"
echo "  1. Increase settle_time in path_generator_params.yaml"
echo ""
echo "If waypoint transitions are too slow:"
echo "  1. Decrease settle_time in path_generator_params.yaml"
echo "  2. Loosen goal_reached_distance"
echo ""

# Step 8: Performance Metrics
echo "Step 8: Performance Metrics to Monitor"
echo ""
echo "Record during one full square loop:"
echo "  - Total time to complete square"
echo "  - Distance error at each waypoint (e_d)"
echo "  - Heading error at each waypoint (e_θ)"
echo "  - Maximum velocity reached"
echo "  - Oscillations at goal"
echo ""
echo "Expected results:"
echo "  - Total time: 30-60 seconds (depends on k_v, v_max)"
echo "  - Final e_d: < 0.05m"
echo "  - Final e_θ: < 0.05 rad"
echo "  - Oscillations: minimal with settle_time=1.0s"
echo ""

echo "=========================================="
echo "Ready to test! Follow the commands above."
echo "=========================================="
