line_follower_node:
  ros__parameters:
    image_topic: '/camera'
    velocity_scale_topic: 'velocity_scale'
    cmd_vel_topic: 'cmd_vel'
    
    line_color: 'white'
    h_lower: 0
    h_upper: 180
    s_lower: 0
    s_upper: 50
    v_lower: 200
    v_upper: 255
    
    roi_start_fraction: 0.67
    roi_end_fraction: 1.0
    
    # --- Configuración PID ---
    kp: 0.5
    ki: 0.05    # Empieza con un valor pequeño
    kd: 0.1
    i_limit: 0.5 # Evita que el robot "pierda la cabeza" si el error persiste
    
    v_base: 0.2
    w_max: 0.8
    control_loop_rate: 0.033
    enable_line_follower: true