line_follower_node:
  ros__parameters:
    image_topic: '/camera'
    velocity_scale_topic: 'velocity_scale'
    cmd_vel_topic: 'cmd_vel'

    line_color: 'black'

    h_lower: 0
    h_upper: 180
    s_lower: 0
    s_upper: 255
    v_lower: 0
    v_upper: 90

    roi_start_fraction: 0.72
    roi_end_fraction: 0.92

    min_line_area: 300.0
    morphology_kernel_size: 5

    # PD
    kp: 0.90
    kd: 0.30

    # Velocidad
    v_base: 0.50
    v_min: 0.28
    v_max: 0.80
    slow_down_error: 0.36

    # Inercia
    max_accel_step: 0.030
    max_decel_step: 0.075

    # Velocidad angular
    w_max: 1.85

    # Si gira al lado contrario, cambia a 1.0
    steering_sign: -1.0

    stop_when_line_lost: true

    control_loop_rate: 0.033
    enable_line_follower: true