traffic_light_controller:
  ros__parameters:
    red_velocity_scale: 0.0
    yellow_velocity_scale: 0.3
    green_velocity_scale: 1.0
    unknown_velocity_scale: 0.0
    color_topic: 'detected_color'
    velocity_scale_topic: 'velocity_scale'
    state_history_length: 3
